sudo: false
language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install -r requires/development.txt
  - pip install -r requires/testing.txt
  - python setup.py develop
script:
  - flake8
  - nosetests
after_success:
  - codecov
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: crad
  on:
    python: 3.7
    tags: true
    all_branches: true
  password:
    secure: "QNndN99rD5boB/Sg3I0CzjkFUF1JmGrsQKZ7ONiA+obUWQDqOmggUoPEs1zN8xIExDcM4tPhlCQX0QiYJrKdLQwWiClvKo1wpYUxVm0s/W8SqvhV3IK9VxhMrbZUkmksO48TH4YKav06rEkVxke9g3U92XUJZ6cRAnYUKrjMYaQ="
