sudo: false
language: python
python:
  - 2.7
  - pypy
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requires/testing.txt
  - python setup.py develop
script: nosetests
after_success:
  - codecov
services:
  - rabbitmq
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: crad
  on:
    python: 3.5
    tags: true
    all_branches: true
  password:
    secure: "QNndN99rD5boB/Sg3I0CzjkFUF1JmGrsQKZ7ONiA+obUWQDqOmggUoPEs1zN8xIExDcM4tPhlCQX0QiYJrKdLQwWiClvKo1wpYUxVm0s/W8SqvhV3IK9VxhMrbZUkmksO48TH4YKav06rEkVxke9g3U92XUJZ6cRAnYUKrjMYaQ="
